The script now warns a user when they haven't configured the .cjdnsadmin file in their home directory

diff --git a/cjdns-onlinepeers b/cjdns-onlinepeers
--- a/cjdns-onlinepeers
+++ b/cjdns-onlinepeers
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 #Online Peers - A script using cjdcmd (https://github.com/inhies/cjdcmd) to check the connectivity of the peers listed in your cjdroute.conf
-#Version: 1.0
+#Version: 1.1
 #License: MIT
 #Issues/ideas: http://gitboria.com/prurigro/cjdns-onlinepeers or prurigro@darkcloud.ca
 
@@ -9,6 +9,12 @@
 CJDROUTE="/etc/cjdroute.conf"
 TMPFILE="/tmp/cjdpeers.tmp"
 JSAWK="/tmp/jsawk.sh"
+
+#Fail if .cjdnsadmin is not configured
+if [ ! -f "$HOME"/.cjdnsadmin ]; then
+  echo "You must configure your "$HOME"/.cjdnsadmin file with your admin credentials before running"
+  exit 1
+fi
 
 #Setup temp file and jsawk
 if [ ! -f "$JSAWK" ]; then
